### PR TITLE
Added new licenses

### PR DESCRIPTION
**Pull request by TheSlowGrowth**
I added a few popular licenses (without their respective logos).

### CODE REVIEW

**Comment by aknuds1** [comment]
Thanks. Does it make sense though to put CC and the other licenses in the same bucket? I'm not a licensing expert at all, but isn't CC applicable to the hardware, whereas e.g. GPL and MIT are applicable to software? Considering MuzHack is a catalog of hardware, would it make sense to have a separate licensing axis for the accompanying software?

**Comment by TheSlowGrowth** [comment]
Yes, you are right. Hence my idea of letting the user add multiple licences, the same way a project can have multiple tags.

**Comment by aknuds1** [comment]
Would it make sense to make the user choose licenses for both hardware and software (let's say this one is optional), so that there's a division between e.g. CC and GPL?

**Comment by TheSlowGrowth** [comment]
Sure that covers most projects. But what would you do for projects that inherit stuff from multiple sources (all having different licenses - see the software world) and thus are licensed under the terms of many different linceses for their respective parts? Especially in the software parts of a project it is easy to gather different libraries that all have their own licenses.

At this stage of the platform it is still easy to implement a scheme that allows for any weird combination of licenses. My idea would be to have a dropdown menu with all the different licenses. The user would then select a license and click an "add" button to add that license to the project. Ideally the user could at the same time sepcify to which part of the project this license applies.

**Comment by aknuds1** [comment]
Sounds like you're onto something. I'll give it a think.

**Comment by aknuds1** [comment]
I will hopefully be able to do something about this soon, as the UI is being re-designed.

**Pull request closed without merging**
